server {
    listen 80;
    server_name enviroo.tech www.enviroo.tech;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name enviroo.tech www.enviroo.tech;

    ssl_certificate /etc/letsencrypt/live/enviroo.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/enviroo.tech/privkey.pem;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
